SOURCE_TO_SBATCH = {
    "CASESM2": "casesm2_10km_nocumulus",
    "ERA5": "era5",
    "ICON": "icon",
    "NICAM": "nicam",
    "SCREAM": "scream",
    "UM": "um_glm_n2560_RAL3p3",
}
"""
Scan ETC variable extraction SLURM log files to find failed jobs for a specified source and print resubmit commands.

This script scans the logs directory for SLURM job array log files generated by submit_etc_extraction_jobs.py,
detects which jobs for a specified source failed (i.e., did not complete variable extraction), and prints the
sbatch command to resubmit the failed jobs for each group.

A job is considered successful if:
- It ends with 'SUCCESS:' (normal case), OR
- It contains 'VARIABLE ... COMPLETED' (output written, even if an error occurred after writing)

Usage:
    python find_failed_etc_jobs.py --source UM
    python find_failed_etc_jobs.py --source ERA5 --logs /path/to/logs

Arguments:
    --source   Source model to check (e.g., UM, ERA5, SCREAM, etc.)
    --logs     Path to logs directory (default: logs directory in this repo)
"""
import argparse
import os
import re
from collections import defaultdict

LOG_DIR = "/global/homes/f/feng045/program/waccem/gsrm_cooccurrencefeature/extract_environments/logs"

def parse_log_filename(filename, source):
    # Example: extract_etc_UM_g0_50472088_0.log
    pattern = rf"extract_etc_{re.escape(source)}_g(\d+)_(\d+)_([0-9]+)\.log"
    m = re.match(pattern, filename)
    if m:
        group = int(m.group(1))
        array_jobid = m.group(2)
        array_taskid = int(m.group(3))
        return group, array_jobid, array_taskid
    return None

def log_success(log_path):
    # A job is considered successful if:
    # - It ends with 'SUCCESS:' (normal case), OR
    # - It contains 'VARIABLE ... COMPLETED' (output written, even if error after)
    with open(log_path, "r") as f:
        lines = [line.strip() for line in f if line.strip()]
    # If any time batch ERROR is present, consider job failed
    for line in lines:
        if "ERROR: Failed to load time slice" in line:
            return False

    for line in reversed(lines):
        if "SUCCESS:" in line:
            return True
        if "FAILED:" in line:
            # Don't return False immediately; check for output written
            continue
        if line.startswith("VARIABLE") and "COMPLETED" in line:
            return True
    return False

def main():
    parser = argparse.ArgumentParser(description="Find failed ETC extraction jobs and print resubmit commands.")
    parser.add_argument("--source", required=True, help="Source model (e.g., UM, ERA5, SCREAM, etc.)")
    parser.add_argument("--logs", default=LOG_DIR, help="Logs directory")
    args = parser.parse_args()

    failed = defaultdict(list)  # group_id -> list of failed array_task_ids

    for fname in os.listdir(args.logs):
        if not fname.startswith(f"extract_etc_{args.source}_g"):
            continue
        parsed = parse_log_filename(fname, args.source)
        if not parsed:
            continue
        group, array_jobid, array_taskid = parsed
        log_path = os.path.join(args.logs, fname)
        if not log_success(log_path):
            failed[group].append(array_taskid)

    if not failed:
        print(f"All jobs for source {args.source} succeeded!")
        return

    print(f"Failed jobs for source {args.source}:")
    sbatch_base = SOURCE_TO_SBATCH.get(args.source, args.source.lower())
    for group, task_ids in sorted(failed.items()):
        task_ids_str = ",".join(str(tid) for tid in sorted(task_ids))
        print(f"  Group {group}: failed array task IDs: {task_ids_str}")
        print(f"  # Resubmit command:")
        print(f"  sbatch --array={task_ids_str} sbatch_{sbatch_base}_g{group}_*.sh")
        print()

if __name__ == "__main__":
    main()