#!/usr/bin/env python
"""
Combine monthly MCS rainmap NetCDF files into a single annual file.

The monthly files are generated by:
- PyFLEXTRKR/Analysis/calc_tbpf_mcs_monthly_rainmap.py

Author: Zhe Feng | zhe.feng@pnnl.gov
"""
import numpy as np
import glob
import xarray as xr

rootdir = "/pscratch/sd/w/wcmca1/hackathon/mcs/"

dir_map = {
    'obs': 'IMERGv7',
    'm1': 'icon_d3hp003',
    'm2': 'ifs_tco3999_rcbmf',
    'm3': 'nicam_gl11',
    'm4': 'scream',
    'm5': 'um_glm_n2560_RAL3p3',
    'm6': 'casesm2_10km_nocumulus',
}

# Loop over each source
for model in dir_map.keys():
    # Set input/output directories and files
    indir = f"{rootdir}{dir_map[model]}/stats/monthly/"
    outdir = indir
    outfile = f"{outdir}mcs_rainmap_monthly.nc"
    infiles = sorted(glob.glob(f"{indir}mcs_rainmap_20*.nc"))

    # Skip if no files found
    if len(infiles) == 0:
        print(f"No files found for {dir_map[model]}, skipping...")
        continue
    else:
        # Read and concatenate data
        print(f"Processing {len(infiles)} files for {model}...")
        ds = xr.open_mfdataset(infiles, concat_dim='time', combine='nested')
        
        fillvalue = np.nan
        # Set encoding/compression for all variables
        comp = dict(zlib=True, _FillValue=fillvalue, dtype='float32')
        encoding = {var: comp for var in ds.data_vars}
        
        # Write to NetCDF - THIS IS WHERE COMPUTATION ACTUALLY HAPPENS!
        print("Writing to NetCDF...")
        ds.to_netcdf(path=outfile, mode='w', format='NETCDF4', unlimited_dims='time', encoding=encoding)
        print(f"Output written to: {outfile}")
